# AppVeyor configuration for AppVeyor project "primordialmachine".
clone_depth: 1

# Build worker image (VM template).
image: Visual Studio 2022

# Build branch "master" only.
branches:
  only:
    - master

# Build platform "x64" and "x86".
platform:
    - x64
    - x86

# Build configurations "Debug" and "Release".
configuration:
    - Release
    - Debug

build:
    parallel: true                       # enable MSBuild parallel builds
    project: machine-mk1/machine-mk1.sln # path to Visual Studio solution or project

# If one matrix entry fails, all entries fails (https://www.appveyor.com/docs/build-configuration#failing-strategy).
matrix:
    fast_finish: true

artifacts:
    - path: machine-mk1\products\x64\Release\machine-mk1\machine-mk1.exe
      name: machine-mk1-x64-release.exe
    - path: machine-mk1\products\x64\Debug\machine-mk1\machine-mk1.exe
      name: machine-mk1-x64-debug.exe
    - path: machine-mk1\products\x86\Release\machine-mk1\machine-mk1.exe
      name: machine-mk1-x86-release.exe
    - path: machine-mk1\products\x86\Debug\machine-mk1\machine-mk1.exe
      name: machine-mk1-x86-debug.exe

# Execute test scripts.
test_script:
    - ps: |
          $name = 'List Test #1';
          Write-Host "Begin Test $name";
          Add-AppveyorTest -Name $name -Filename a.exe -Outcome Running;
          Update-AppveyorTest -Name $name -Filename a.exe -Outcome Passed -Duration 1000;
          Write-Host "End Test $name";

    - ps: |
          $name = 'Map Test #1';
          Write-Host "Begin Test $name";
          Add-AppveyorTest -Name "$name" -Filename a.exe -Outcome Running;
          Update-AppveyorTest -Name "$name" -Filename a.exe -Outcome Passed -Duration 1000;
          Write-Host "End Test $name";
