DefineSignal(MouseButtonPresssed, "mouse-button-pressed")
DefineSignal(MouseButtonReleased, "mouse-button-released")
DefineSignal(MousePointerMoved, "mouse-pointer-moved")
DefineSignal(KeybordKeyPresssed, "keyboard-key-pressed")
DefineSignal(KeyboardKeyReleased, "keybaord-key-released")
DefineSignal(KeyboardKeyRepeated, "keyboard-key-repeated")
