#if !defined(RING1_INTRINSIC_ADD_CONFIGURATION_H_INCLUDED)
#define RING1_INTRINSIC_ADD_CONFIGURATION_H_INCLUDED

#define RING1_INTRINSIC_ADD_CONFIGURATION_WITHWINAPI (1)

#endif // RING1_INTRINSIC_ADD_CONFIGURATION_H_INCLUDED
