/* Copyright (c) 2020 Michael Heilmann. All rights reserved. */

/// @remark Simply using "NULL" as the name would make C choke.
DEFINE(NULL_LITERAL, "NULL")

DEFINE(VOID, "g_void")



DEFINE(BOOLEAN, "g_boolean")
DEFINE(BOOLEAN_DEFAULT_VALUE, "G_BOOLEAN_DEFAULT_VALUE")



DEFINE(INTEGER_DEFAULT_VALUE, "G_INTEGER_DEFAULT_VALUE")



DEFINE(NATURAL_DEFAULT_VALUE, "G_NATURAL_DEFAULT_VALUE")



DEFINE(INTEGER8_DEFAULT_VALUE, "G_INTEGER8_DEFAULT_VALUE")

DEFINE(INTEGER16_DEFAULT_VALUE, "G_INTEGER16_DEFAULT_VALUE")

DEFINE(INTEGER32_DEFAULT_VALUE, "G_INTEGER32_DEFAULT_VALUE")

DEFINE(INTEGER64_DEFAULT_VALUE, "G_INTEGER64_DEFAULT_VALUE")



DEFINE(NATURAL8_DEFAULT_VALUE, "G_NATURAL8_DEFAULT_VALUE")

DEFINE(NATURAL16_DEFAULT_VALUE, "G_NATURAL16_DEFAULT_VALUE")

DEFINE(NATURAL32_DEFAULT_VALUE, "G_NATURAL32_DEFAULT_VALUE")

DEFINE(NATURAL64_DEFAULT_VALUE, "G_NATURAL64_DEFAULT_VALUE")



DEFINE(SIZE_DEFAULT_VALUE, "G_NATURAL64_DEFAULT_VALUE")



DEFINE(REFERENCE_NULL_VALUE, "NULL")
DEFINE(REFERENCE_DEFAULT_VALUE, "NULL")



DEFINE(PARENT, "parent")



DEFINE(EMPTY, "")



DEFINE(G_VIRTUALCALL, "G_VIRTUALCALL")
DEFINE(G_VIRTUALCALL_NO_RESULT, "G_VIRTUALCALL_NO_RESULT")
