# AppVeyor configuration for AppVeyor project "primordialmachine".
clone_depth: 1

# Build worker image (VM template).
image: Visual Studio 2022

# Build branch "master" only.
branches:
  only:
    - master

# Build platform "x64" and "x86".
platform:
    - x64
    - x86

# Build configurations "Debug" and "Release".
configuration:
    - Release
    - Debug

build:
    parallel: true                       # enable MSBuild parallel builds
    project: Ring2/Ring2.sln             # path to Visual Studio solution or project

# If one matrix entry fails, all entries fails (https://www.appveyor.com/docs/build-configuration#failing-strategy).
matrix:
    fast_finish: true

artifacts:
    - path: ring2\products\$(platform)\$(configuration)\Ring2.Library.Test\Ring2.Library.Test.exe
      name: Ring2.Library.Test-$(platform)-$(configuration).exe

# Execute test scripts.
test_script:
    - ps: |
          $name = 'Ring2.Library.Test';
          $prefix = "${env:appveyor_build_folder}\Ring2\products\${env:platform}\${env:configuration}\Ring2.Library.Test";
          $suffix = 'Ring2.Library.Test.exe';
          [int]$startMs = (Get-Date).Millisecond
          cd ${prefix}
          Invoke-Expression "./${suffix}"
          $code = $LastExitCode
          [int]$endMs = (Get-Date).Millisecond
          if ($code -eq 0) {
            Add-AppveyorTest -Name ${name} -Filename "${prefix}\${suffix}" -Outcome Passed -Duration $($endMs - $startMs);
          } else {
            Add-AppveyorTest -Name ${name} -Filename "${prefix}\${suffix}" -Outcome Failed -Duration $($endMs - $startMs);
          }
